### ISSUE TITLE
What are the parameters for Figure S2

### ISSUE THREAD

**Issue by liux0614** [diazale/1KGP_dimred#4]
I tried to reproduce the results in Figure S2 (# princial components = 15). However, the results are different from what are shown in the supporting materials. I was just wondering if you could provide me the specific parameters for UMAP.

Below is my experiment configuration:
I first applied PCA to the transposed_genotype_matrix to get the proj_pca. Then I applied UMAP to proj_pca[:,:15] with n_components=2, n_neighbors=15, min_dist=0.5.

**Comment by diazale** [comment]
Those are the parameters I used. Can you specify how the results were different?

**Comment by diazale** [comment]
Closing this issue as inactive. I will note that UMAP will generally not recreate the same embedding every time unless you fix a random seed beforehand.
